/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 38;
=======
const int buildversion = 103;
>>>>>>> Nico
const char buildconfig[] = "SHELL_PROJECT";
